version: "3"
services:
  database:
    image: postgres:11.6-alpine
    container_name: hedgedoc_db
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
    networks:
      intranet:
  hedgedoc:
    container_name: hegedoc
    image: quay.io/hedgedoc/hedgedoc:1.7.1
    environment:
      - CMD_DB_URL=postgres://hedgedoc:${DB_PASSWORD}@hedgedoc_db/hedgedoc
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_IMAGE_UPLOAD_FILESYSTEN=filesystem
      - CMD_USECDN=false
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    ports:
      - "3000:3000"
    networks:
      intranet:
      www:
    restart: always
    depends_on:
      - database

networks:
  intranet:
    external: true
  www:
    external: true

volumes:
  database-data: {}
  upload-data: {}
