version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
     - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    command: -H unix:///var/run/docker.sock
    restart: always
networks:
  default:
    external:
      name: ${NETWORK}
volumes:
  data: {}
